// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcrsuvzsqivcamzlvluz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjcnN1dnpzcWl2Y2Ftemx2bHV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NjMxMTAsImV4cCI6MjA3NjMzOTExMH0.cSGUbpqtGnILrRUTt2tgN-z31OjnMbm730FI7Vi3vkw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});