// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jspsuwpboewyffxrnzpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpzcHN1d3Bib2V3eWZmeHJuenBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODE4OTYyNjUsImV4cCI6MjA5NzQ3MjI2NX0.eRIVUaOZ05fUlVl4yM0z9ICdFCYVLKS1hki4T2VOfdY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});